# Wine Quality — pipeline reproduzível (R base)
raiz <- normalizePath("."); caminho <- function(...) file.path(raiz, ...)
for (p in c("03_DADOS_LIMPOS","06_GRAFICOS","07_TABELAS")) dir.create(caminho(p),showWarnings=FALSE,recursive=TRUE)
bruto <- read.csv(caminho("01_DADOS_BRUTOS","winequality-red.csv"),check.names=FALSE)
names(bruto) <- gsub("(^_|_$)","",gsub("[^a-z0-9]+","_",tolower(names(bruto))))
limpo <- bruto[!duplicated(bruto),]; limpo$quality_group <- ifelse(limpo$quality>=7,"alta",ifelse(limpo$quality>=6,"media","baixa"))
write.csv(data.frame(linhas_brutas=nrow(bruto),linhas_limpas=nrow(limpo),colunas=ncol(limpo),ausentes=sum(is.na(limpo)),duplicados_removidos=nrow(bruto)-nrow(limpo)),caminho("07_TABELAS","validacao_limpeza.csv"),row.names=FALSE)
write.csv(limpo,caminho("03_DADOS_LIMPOS","wine_quality_limpo.csv"),row.names=FALSE)
por_qualidade <- data.frame(quality=sort(unique(limpo$quality)),quantidade=as.integer(table(limpo$quality)[as.character(sort(unique(limpo$quality)))]))
write.csv(por_qualidade,caminho("07_TABELAS","distribuicao_qualidade.csv"),row.names=FALSE)
png(caminho("06_GRAFICOS","distribuicao_qualidade.png"),1440,900,res=150);barplot(por_qualidade$quantidade,names.arg=por_qualidade$quality,col="#8C6BB1",xlab="Qualidade",ylab="Número de vinhos",main="Distribuição da qualidade do vinho");dev.off()
cat("Pipeline Wine Quality concluído.\n")
